source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!
target 'LicenseParser_Tests' do
  pod 'LicenseParser', :path => '../'

  pod 'Quick', "~> 0.9"
  pod 'Nimble', "~> 4.1"
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
end
