# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - gem update concurrent-ruby
  - pod setup
#  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/LicenseParser.xcworkspace -scheme LicenseParser-Example -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone x,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
